- hosts: homeautomation
  #https://www.home-assistant.io/docs/installation/raspberry-pi/
  remote_user: pi
  become: yes
  tasks:
    - name: SystemUpdate
      apt:
        upgrade: yes
        update_cache: yes
        autoclean: yes
        autoremove: yes
    - name: InstallDependencies
      apt:
        pkg:
          - python3
          - python3-dev
          - python3-venv
          - python3-pip
          - libffi-dev
          - libssl-dev
          - screen
          - mc
          - cockpit
    - name: AddUserhomeassistant
      user:
        name: homeassistant
        create_home: yes
        system: yes
        groups: dialout,gpio,i2c
    - name: CreatehomeassistantDirectory
      file:
        path: /srv/homeassistant
        state: directory
        owner: homeassistant
        group: homeassistant
