- hosts: homeautomation
  remote_user: pi
  become: yes
  tasks:
    - name: staticip
      blockinfile:
        path: /etc/dhcpcd.conf
        block: |
          interface wlan0
          static ip_address=192.168.1.209/24
          static routers=192.168.1.1
          static domain_name_servers=8.8.8.8
