# UUID=4A75-A30E /mnt/linuxbackup
# UUID=c74a8913-e309-4779-a241-158277d61a04 /mnt/calibre ext3
# UUID=fa8e08c4-a62a-4bbf-92c6-da9d9afc06f0 /mnt/owncloud ext4
# UUID=93e0ee1a-6010-451e-acc5-8ac08c6c05f3 /mnt/windowsbackup ext3

- hosts: homeautomation
  remote_user: pi
  become: yes
  tasks:
    - name: Install Samba packages
      apt:
        update_cache: yes
        pkg:
          - samba
          - samba-common-bin
    - name: Configure Samba
      blockinfile:
        path: /etc/samba/smb.conf
        block: |
          [LinuxBackup]
          path = /mnt/linuxbackup
          writeable = yes
          create mask=0777
          directory mask=0777
          public=yes

          [Calibre]
          path = /mnt/calibre
          writeable = yes
          create mask=0777
          directory mask=0777
          public=yes

          [OwnCloud]
          path = /mnt/owncloud
          writeable = yes
          create mask=0777
          directory mask=0777
          public=yes

          [WindowsBackup]
          path = /mnt/windowsbackup
          writeable = yes
          create mask=0777
          directory mask=0777
          public=yes
    - name: Restart Samba server
      systemd:
        service: smbd
        state: restarted
